name: Build and Deploy
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone comobi-core repository
        run: |
          git clone -b addSpecFiles --depth 1 https://github.com/betagouv/comobi-core.git .

      - name: Clone specific repository
        run: |
          git clone --depth 1 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} specific
      - name: Override generic files with specific ones
        run: |
          mv specific/* .
      - name: Install and Build ðŸ”§
        run: |
          npm install
          npm run build:direct
      - name: Build and Push Jekyll site
        uses: helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
        with:
          target_branch: 'deploy'
          jekyll_src: .
      
